name: Build EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Build with PyInstaller
      run: |
        cd scorebug
        pyinstaller server.spec

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: VolleyScore-Scorebug.zip
        path: scorebug/dist/server.exe